TOURNAMENT_STATUS_UPCOMING = 'upcoming'
TOURNAMENT_STATUS_ACTIVE = 'active'
TOURNAMENT_STATUS_COMPLETED = 'completed'
TOURNAMENT_STATUS_ARCHIVED = 'archived'
TOURNAMENT_STATUS_CHOICES = [
    (TOURNAMENT_STATUS_UPCOMING, 'Upcoming'),
    (TOURNAMENT_STATUS_ACTIVE, 'Active'),
    (TOURNAMENT_STATUS_COMPLETED, 'Completed'),
    (TOURNAMENT_STATUS_ARCHIVED, 'Archived'),
]
DEFAULT_ELO_RATING = 1200
MATCH_WIN_POINTS = 1
MATCH_LOSE_POINTS = 0
TEAM_SIZE_LIMIT = 6
PLAYER_NICKNAME_MAX_LENGTH = 64
TEAM_NAME_MAX_LENGTH = 100
TOURNAMENT_NAME_MAX_LENGTH = 128
